import { type CSSProperties } from "react";

// ============================================================================
// COMPLETE EDITOR STYLES
// ============================================================================

export const editorStyles: Record<string, CSSProperties> = {
  // Main Container
  container: {
    display: "flex",
    height: "100vh",
    width: "100%",
    backgroundColor: "#0f0f0f",
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
    color: "#e5e5e5",
    overflow: "hidden",
  },

  // Left Sidebar
  leftSidebar: {
    width: "60px",
    minWidth: "60px",
    backgroundColor: "#0a0a0a",
    borderRight: "1px solid rgba(255,255,255,0.08)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    paddingTop: "16px",
    gap: "8px",
  },
  sidebarButton: {
    width: "44px",
    height: "44px",
    border: "none",
    backgroundColor: "transparent",
    color: "#666",
    cursor: "pointer",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "4px",
    borderRadius: "8px",
    transition: "all 0.15s",
    fontSize: "9px",
    fontWeight: 500,
  },
  sidebarButtonActive: {
    color: "#3b82f6",
    backgroundColor: "rgba(59, 130, 246, 0.1)",
  },
  sidebarBackButton: {
    width: "44px",
    height: "44px",
    border: "none",
    backgroundColor: "transparent",
    color: "#666",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "8px",
    transition: "all 0.15s",
    marginBottom: "16px",
    borderBottom: "1px solid rgba(255,255,255,0.08)",
    paddingBottom: "16px",
  },

  // Layers Panel
  layersPanel: {
    width: "320px",
    minWidth: "320px",
    backgroundColor: "#141414",
    borderRight: "1px solid rgba(255,255,255,0.08)",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    transition: "width 0.2s ease, min-width 0.2s ease, opacity 0.2s ease",
  },
  layersPanelClosed: {
    width: "0px",
    minWidth: "0px",
    borderRight: "none",
    opacity: 0,
  },
  layersPanelHeader: {
    padding: "16px",
    borderBottom: "1px solid rgba(255,255,255,0.08)",
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  layersPanelTitle: {
    fontSize: "13px",
    fontWeight: "600",
    color: "#e5e5e5",
    flex: 1,
  },
  headerButtons: {
    display: "flex",
    gap: "4px",
  },
  addLayerButton: {
    width: "28px",
    height: "28px",
    border: "1px solid rgba(255,255,255,0.1)",
    backgroundColor: "transparent",
    color: "#888",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "6px",
    transition: "all 0.15s",
  },
  closeButton: {
    width: "28px",
    height: "28px",
    border: "1px solid rgba(255,255,255,0.1)",
    backgroundColor: "transparent",
    color: "#666",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "6px",
    transition: "all 0.15s",
  },
  layersList: {
    flex: 1,
    overflowY: "auto",
    padding: "8px",
  },
  layerItem: {
    padding: "10px 12px",
    borderRadius: "6px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "10px",
    marginBottom: "4px",
    transition: "all 0.15s",
    backgroundColor: "transparent",
    border: "1px solid transparent",
  },
  layerItemActive: {
    backgroundColor: "rgba(59, 130, 246, 0.15)",
    border: "1px solid rgba(59, 130, 246, 0.3)",
  },
  layerIcon: {
    width: "24px",
    height: "24px",
    borderRadius: "4px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  layerName: {
    fontSize: "12px",
    fontWeight: "500",
    color: "#e5e5e5",
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  layerType: {
    fontSize: "10px",
    color: "#666",
    textTransform: "uppercase",
  },

  // Edit Panel
  editPanel: {
    width: "320px",
    minWidth: "320px",
    backgroundColor: "#141414",
    borderRight: "1px solid rgba(255,255,255,0.08)",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    transition: "width 0.2s ease, min-width 0.2s ease, opacity 0.2s ease",
  },
  editPanelHidden: {
    width: 0,
    minWidth: 0,
    opacity: 0,
    overflow: "hidden",
  },
  editPanelHeader: {
    padding: "16px",
    borderBottom: "1px solid rgba(255,255,255,0.08)",
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  backButton: {
    width: "32px",
    height: "32px",
    border: "none",
    backgroundColor: "transparent",
    color: "#888",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "6px",
    transition: "all 0.15s",
  },
  editPanelTitle: {
    fontSize: "14px",
    fontWeight: "600",
    color: "#e5e5e5",
  },
  editPanelContent: {
    flex: 1,
    overflowY: "auto",
    padding: "16px",
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },

  // Form Elements
  textInput: {
    width: "100%",
    padding: "12px",
    backgroundColor: "#1a1a1a",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: "8px",
    color: "#e5e5e5",
    fontSize: "14px",
    outline: "none",
    resize: "none",
    minHeight: "80px",
    fontFamily: "inherit",
  },
  styleSection: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
  },
  styleLabel: {
    fontSize: "12px",
    fontWeight: "600",
    color: "#888",
  },
  fontSelect: {
    flex: 1,
    padding: "10px 12px",
    backgroundColor: "#1a1a1a",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: "8px",
    color: "#e5e5e5",
    fontSize: "13px",
    outline: "none",
    cursor: "pointer",
    appearance: "none",
    backgroundImage: `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 24 24' fill='none' stroke='%23666' stroke-width='2'%3E%3Cpath d='M6 9l6 6 6-6'/%3E%3C/svg%3E")`,
    backgroundRepeat: "no-repeat",
    backgroundPosition: "right 12px center",
  },
  weightSizeRow: {
    display: "flex",
    gap: "8px",
    alignItems: "center",
  },
  weightSelect: {
    flex: 1,
    padding: "10px 12px",
    backgroundColor: "#1a1a1a",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: "8px",
    color: "#e5e5e5",
    fontSize: "13px",
    outline: "none",
    cursor: "pointer",
    appearance: "none",
    backgroundImage: `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' viewBox='0 0 24 24' fill='none' stroke='%23666' stroke-width='2'%3E%3Cpath d='M6 9l6 6 6-6'/%3E%3C/svg%3E")`,
    backgroundRepeat: "no-repeat",
    backgroundPosition: "right 12px center",
  },
  sizeInput: {
    width: "70px",
    padding: "10px 12px",
    backgroundColor: "#1a1a1a",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: "8px",
    color: "#e5e5e5",
    fontSize: "13px",
    outline: "none",
    textAlign: "center",
  },
  colorCircle: {
    width: "36px",
    height: "36px",
    borderRadius: "50%",
    border: "2px solid rgba(255,255,255,0.2)",
    cursor: "pointer",
    position: "relative",
    overflow: "hidden",
    flexShrink: 0,
  },
  colorInput: {
    position: "absolute",
    inset: 0,
    opacity: 0,
    cursor: "pointer",
    width: "100%",
    height: "100%",
  },
  styleButtonsRow: {
    display: "flex",
    gap: "4px",
    alignItems: "center",
  },
  styleButton: {
    width: "36px",
    height: "36px",
    border: "1px solid rgba(255,255,255,0.1)",
    backgroundColor: "#1a1a1a",
    color: "#888",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: "6px",
    transition: "all 0.15s",
  },
  styleButtonActive: {
    backgroundColor: "rgba(59, 130, 246, 0.2)",
    borderColor: "#3b82f6",
    color: "#3b82f6",
  },
  toggleRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "8px 0",
  },
  toggleLabel: {
    fontSize: "13px",
    color: "#e5e5e5",
  },
  toggle: {
    width: "44px",
    height: "24px",
    borderRadius: "12px",
    backgroundColor: "rgba(255,255,255,0.1)",
    border: "none",
    cursor: "pointer",
    position: "relative",
    transition: "background-color 0.2s",
  },
  toggleActive: {
    backgroundColor: "#3b82f6",
  },
  toggleKnob: {
    position: "absolute",
    top: "2px",
    left: "2px",
    width: "20px",
    height: "20px",
    borderRadius: "50%",
    backgroundColor: "white",
    transition: "transform 0.2s",
  },
  toggleKnobActive: {
    transform: "translateX(20px)",
  },
  colorRow: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  sliderRow: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  sliderLabel: {
    width: "40px",
    fontSize: "12px",
    color: "#666",
  },
  slider: {
    flex: 1,
    height: "4px",
    borderRadius: "2px",
    appearance: "none",
    backgroundColor: "rgba(255,255,255,0.1)",
    cursor: "pointer",
    outline: "none",
  },
  sliderValue: {
    width: "50px",
    padding: "6px 8px",
    backgroundColor: "#1a1a1a",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: "6px",
    color: "#e5e5e5",
    fontSize: "12px",
    textAlign: "center",
    outline: "none",
  },
  deleteButton: {
    width: "100%",
    padding: "12px",
    backgroundColor: "transparent",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: "8px",
    color: "#888",
    fontSize: "13px",
    cursor: "pointer",
    transition: "all 0.15s",
    marginTop: "auto",
  },

  // Main Area
  mainArea: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  header: {
    height: "56px",
    padding: "0 20px",
    borderBottom: "1px solid rgba(255,255,255,0.08)",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#0f0f0f",
  },
  headerTitle: {
    fontSize: "14px",
    fontWeight: "600",
    color: "#e5e5e5",
  },
  headerButtonsRight: {
    display: "flex",
    gap: "8px",
  },
  addButton: {
    padding: "8px 16px",
    backgroundColor: "rgba(59, 130, 246, 0.1)",
    border: "1px solid rgba(59, 130, 246, 0.3)",
    borderRadius: "8px",
    color: "#3b82f6",
    fontSize: "13px",
    fontWeight: "500",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "6px",
    transition: "all 0.2s",
  },
  exportButton: {
    padding: "8px 16px",
    background: "linear-gradient(135deg, #6366f1 0%, #4f46e5 100%)",
    border: "none",
    borderRadius: "8px",
    color: "white",
    fontSize: "13px",
    fontWeight: "600",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  previewArea: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#0a0a0a",
    position: "relative",
  },
  previewWrapper: {
    position: "relative",
    width: "calc(65vh * 0.5625)",
    height: "65vh",
  },

  // Video Library Styles
  videoLibraryContainer: {
    padding: "10px",
    overflowY: "auto",
    height: "100%",
  },
  videoLibraryHeader: {
    display: "flex",
    gap: "6px",
    marginBottom: "12px",
  },
  viewAssetsButton: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "4px",
    padding: "6px 10px",
    background: "#3b82f6",
    color: "white",
    border: "none",
    borderRadius: "5px",
    cursor: "pointer",
    fontSize: "11px",
    fontWeight: "500",
    transition: "all 0.2s",
  },
  uploadFileButton: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "4px",
    padding: "6px 10px",
    background: "white",
    color: "#333",
    border: "1px solid #e5e7eb",
    borderRadius: "5px",
    cursor: "pointer",
    fontSize: "11px",
    fontWeight: "500",
    transition: "all 0.2s",
  },
  videoSection: {
    marginBottom: "16px",
  },
  videoSectionHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "8px",
  },
  videoSectionTitle: {
    fontSize: "12px",
    fontWeight: "600",
    color: "#e5e5e5",
    margin: 0,
  },
  viewMoreLink: {
    background: "none",
    border: "none",
    color: "#3b82f6",
    cursor: "pointer",
    fontSize: "10px",
    padding: "0",
    textDecoration: "none",
  },
  videoGridVertical: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "6px",
    marginBottom: "8px",
  },
  videoCardVertical: {
    cursor: "pointer",
    transition: "opacity 0.2s",
  },
  videoThumbnailVertical: {
    position: "relative",
    width: "100%",
    height: "50px",
    borderRadius: "4px",
    overflow: "hidden",
    marginBottom: "4px",
    backgroundColor: "#1a1a1a",
  },
  videoThumbnailImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  videoDurationBadge: {
    position: "absolute",
    bottom: "4px",
    left: "4px",
    background: "rgba(0, 0, 0, 0.8)",
    color: "white",
    padding: "1px 4px",
    borderRadius: "2px",
    fontSize: "9px",
    fontWeight: "500",
  },
  videoNameText: {
    fontSize: "10px",
    color: "#e5e5e5",
    marginBottom: "3px",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  videoProgressSlider: {
    width: "100%",
    height: "3px",
    cursor: "pointer",
    appearance: "none",
    backgroundColor: "#333",
    borderRadius: "2px",
    outline: "none",
  },

  // Video Edit Panel Styles
  propertyRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "10px",
  },
  propertyValue: {
    fontSize: "13px",
    fontWeight: "600",
    color: "#3b82f6",
    backgroundColor: "rgba(59,130,246,0.1)",
    padding: "4px 10px",
    borderRadius: "6px",
  },
  propertyGroup: {
    marginBottom: "20px",
  },
  propertyLabel: {
    fontSize: "14px",
    fontWeight: "600",
    color: "#e5e5e5",
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  speedButtons: {
    display: "flex",
    gap: "8px",
  },
  speedButton: {
    flex: 1,
    padding: "10px 8px",
    background: "linear-gradient(135deg, #1f1f1f 0%, #2a2a2a 100%)",
    color: "#e5e5e5",
    border: "1px solid #404040",
    borderRadius: "8px",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: "600",
    transition: "all 0.2s",
    boxShadow: "0 2px 4px rgba(0,0,0,0.2)",
  },
  speedButtonActive: {
    background: "linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)",
    borderColor: "#3b82f6",
    color: "white",
    boxShadow: "0 4px 12px rgba(59,130,246,0.4)",
  },
  checkboxLabel: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    color: "#e5e5e5",
    fontSize: "14px",
    cursor: "pointer",
  },
  rotationControls: {
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  rotationInput: {
    width: "60px",
    padding: "8px",
    background: "linear-gradient(135deg, #1f1f1f 0%, #2a2a2a 100%)",
    border: "1px solid #404040",
    borderRadius: "6px",
    color: "#e5e5e5",
    fontSize: "14px",
    fontWeight: "600",
    textAlign: "center",
    boxShadow: "inset 0 2px 4px rgba(0,0,0,0.2)",
  },
  degreeSymbol: {
    color: "#999",
    fontSize: "14px",
    fontWeight: "600",
  },
  flipButton: {
    padding: "8px 12px",
    background: "linear-gradient(135deg, #1f1f1f 0%, #2a2a2a 100%)",
    border: "1px solid #404040",
    borderRadius: "6px",
    color: "#e5e5e5",
    cursor: "pointer",
    fontSize: "18px",
    transition: "all 0.2s",
    boxShadow: "0 2px 4px rgba(0,0,0,0.2)",
  },
  resetButtons: {
    display: "flex",
    gap: "8px",
  },
  resetButton: {
    padding: "6px 14px",
    background: "linear-gradient(135deg, #1f1f1f 0%, #2a2a2a 100%)",
    border: "1px solid #404040",
    borderRadius: "6px",
    color: "#999",
    cursor: "pointer",
    fontSize: "12px",
    fontWeight: "600",
    transition: "all 0.2s",
    boxShadow: "0 2px 4px rgba(0,0,0,0.2)",
  },
  filterPresets: {
    display: "flex",
    gap: "8px",
  },
  filterPresetButton: {
    flex: 1,
    padding: "10px 12px",
    background: "linear-gradient(135deg, #1f1f1f 0%, #2a2a2a 100%)",
    border: "1px solid #404040",
    borderRadius: "8px",
    color: "#e5e5e5",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: "600",
    transition: "all 0.2s",
    boxShadow: "0 2px 4px rgba(0,0,0,0.2)",
  },
  filterPresetActive: {
    background: "linear-gradient(135deg, #f59e0b 0%, #d97706 100%)",
    borderColor: "#f59e0b",
    color: "white",
    boxShadow: "0 4px 12px rgba(245,158,11,0.4)",
  },
  positionGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "8px",
  },
  positionButton: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "6px",
    padding: "12px 10px",
    background: "linear-gradient(135deg, #1f1f1f 0%, #2a2a2a 100%)",
    border: "1px solid #404040",
    borderRadius: "8px",
    color: "#e5e5e5",
    cursor: "pointer",
    fontSize: "12px",
    fontWeight: "600",
    transition: "all 0.2s",
    boxShadow: "0 2px 4px rgba(0,0,0,0.2)",
  },
  positionButtonActive: {
    background: "linear-gradient(135deg, #3b82f6 0%, #2563eb 100%)",
    borderColor: "#3b82f6",
    color: "white",
    boxShadow: "0 4px 12px rgba(59,130,246,0.4)",
  },
  replaceVideoButton: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    padding: "14px 12px",
    background: "linear-gradient(135deg, #1f1f1f 0%, #2a2a2a 100%)",
    border: "1px solid #404040",
    borderRadius: "8px",
    color: "#e5e5e5",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "600",
    marginTop: "16px",
    transition: "all 0.2s",
    boxShadow: "0 2px 4px rgba(0,0,0,0.2)",
  },
  deleteVideoButton: {
    width: "48px",
    height: "48px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "linear-gradient(135deg, #dc2626 0%, #b91c1c 100%)",
    border: "none",
    borderRadius: "8px",
    color: "white",
    cursor: "pointer",
    marginTop: "12px",
    marginLeft: "auto",
    transition: "all 0.2s",
    boxShadow: "0 4px 12px rgba(220,38,38,0.4)",
  },
};