// ============================================================================
// LAYER UTILITY FUNCTIONS
// ============================================================================

import type {
  Layer,
  TextLayer,
  ImageLayer,
} from "../../remotion_compositions/DynamicLayerComposition";
import { FPS, DEFAULT_BACKGROUND } from "../constants";

export const generateId = () => `layer_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`;

export const createDefaultLayers = (duration: number): Layer[] => [
  {
    id: "bg_default",
    type: "image",
    name: "Background",
    visible: true,
    locked: false,
    startFrame: 0,
    endFrame: duration * FPS,
    position: { x: 50, y: 50 },
    size: { width: 100, height: 100 },
    rotation: 0,
    opacity: 1,
    src: DEFAULT_BACKGROUND,
    isBackground: true,
    objectFit: "cover",
    filter: "brightness(0.6)",
  } as ImageLayer,
  {
    id: "text_quote",
    type: "text",
    name: "Quote",
    visible: true,
    locked: false,
    startFrame: Math.round(duration * FPS * 0.1),
    endFrame: duration * FPS,
    position: { x: 50, y: 40 },
    size: { width: 80, height: 25 },
    rotation: 0,
    opacity: 1,
    content: "Your inspiring quote goes here",
    fontFamily: "Roboto, sans-serif",
    fontSize: 5,
    fontColor: "#ffffff",
    fontWeight: "normal",
    fontStyle: "normal",
    textAlign: "center",
    lineHeight: 1.5,
    textOutline: true,
    outlineColor: "#000000",
    textShadow: true,
    shadowColor: "#000000",
    shadowX: 2,
    shadowY: 2,
    shadowBlur: 4,
    animation: { entrance: "slideUp", entranceDuration: 45 },
  } as TextLayer,
  {
    id: "text_author",
    type: "text",
    name: "Author",
    visible: true,
    locked: false,
    startFrame: Math.round(duration * FPS * 0.5),
    endFrame: duration * FPS,
    position: { x: 50, y: 75 },
    size: { width: 60, height: 10 },
    rotation: 0,
    opacity: 1,
    content: "— Author Name",
    fontFamily: "Roboto, sans-serif",
    fontSize: 2.5,
    fontColor: "#ffffff",
    fontWeight: "600",
    fontStyle: "normal",
    textAlign: "center",
    lineHeight: 1.4,
    textTransform: "uppercase",
    letterSpacing: 2,
    textOutline: false,
    outlineColor: "#000000",
    textShadow: false,
    shadowColor: "#000000",
    shadowX: 0,
    shadowY: 0,
    shadowBlur: 0,
    animation: { entrance: "fade", entranceDuration: 30 },
  } as TextLayer,
];